dbt_practice:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: dbt_dev
      threads: 1
      keepalives_idle: 0
      connect_timeout: 10
