dbt_practice:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5432
      schema: dbt_dev
      threads: 1
      type: postgres
      user: postgres
  target: dev
elementary:
  outputs:
    dev:
      connect_timeout: 10
      dbname: postgres
      host: localhost
      keepalives_idle: 0
      password: postgres
      port: 5432
      schema: dbt_dev_elementary
      threads: 1
      type: postgres
      user: postgres
  target: dev
